### ISSUE TITLE
missing particle texture

### ISSUE THREAD

**Issue by Aleruslio** [team-abnormals/abnormals-delight#61] opened 2023-02-15 06:06 UTC
there's no particle texture while cutting a turkey on cutting board
![image](https://user-images.githubusercontent.com/100682849/218946107-af8b5e08-2c05-4cd6-8b13-13a2a8633453.png)
1.18.2 - abnormals delight 3.0.2

**Comment by bageldotjpg** [comment] 2023-02-15 13:55
Duplicate of #20

**Closed as completed by bageldotjpg** 2023-02-15 13:55 UTC
